[package]
name = "javascript-v8"
version = "0.1.0"
authors = ["Yufei Huang <yufeih@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty_v8 = "0.13.0"
