name: build
on:
  push:
    branches:
    - main
    tags:
    - 'v*.*.*'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - run: cargo build --release
      working-directory: rust
    - run: dotnet test -c Release
      working-directory: dotnet

    - uses: actions/upload-artifact@v2
      with:
        name: lib-${{ matrix.os }}
        path: rust/target/release/*docfxjsv8*.*

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - uses: actions/download-artifact@v2
      with:
        name: lib-windows-latest
        path: rust/target/release
    - uses: actions/download-artifact@v2
      with:
        name: lib-macos-latest
        path: rust/target/release
    - uses: actions/download-artifact@v2
      with:
        name: lib-ubuntu-latest
        path: rust/target/release
    - run: dotnet test -c Release
      working-directory: dotnet
    - run: >
        dotnet pack -c Release -o $RUNNER_TEMP/nuget
        /p:Version=1.0.0-${GITHUB_REF#refs/heads/}-${GITHUB_RUN_NUMBER}
        /p:InformationalVersion=1.0.0-${GITHUB_REF#refs/heads/}-${GITHUB_RUN_NUMBER}-${GITHUB_SHA::8}
      working-directory: dotnet
    - run: dotnet nuget push $RUNNER_TEMP/nuget/*.nupkg --api-key $env:NUGET_KEY --source https://api.nuget.org/v3/index.json
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
