name: Build
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    # cargo
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cargo test --release --all-features
    - run: cargo build --release --all-features

    # dotnet
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - run: dotnet test -c Release
    - run: dotnet pack -c Release $pwd/drop

    # publish
    - if: |
        (github.event_name == 'create' && github.event.ref_type == 'tag') ||
        (github.event_name == 'push' && github.event.ref == 'refs/heads/preview')
      run: dotnet nuget push drop/**/*.nupkg --api-key $env:NUGET_KEY --source https://nuget.org
      env:
        NUGET_KEY: ${{ secrets.NUGET_KEY }}